name = "grok-chat"
type = "javascript"

account_id = "你的账户ID"
workers_dev = true
compatibility_date = "2025-03-06"

[env.production]
workers_dev = false
compatibility_date = "2025-03-06"

[build]
command = "npm install"
entry-point = "_worker.js"
